
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn clean compile assembly:single

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/leusonmario/HikariCP/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-1f0b022bc38616317d3aa10d18160b7cfbcf8e95
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            